### ISSUE TITLE
Unable to get fr translations

### ISSUE THREAD

**Issue by ncharlot** [alexandrevicenzi/Flex#74]
Hi!

We're launching a blog in french only.
After many tries, can't get translations. Still "Posted on..." rather than "Posté le ...".

This is the conf:
```python
# Default theme language.
I18N_TEMPLATES_LANG = 'fr'
DEFAULT_LANG = 'fr'
LOCALE = 'fr_FR'
OG_LOCALE = 'fr_FR'

JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}

PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = ['i18n_subsites']
```

Do we really need `i18n_subsites` module?

Thanks for your help.

**Comment by alexandrevicenzi** [comment]
Hi

# Default theme language.
# You can't change this one.
I18N_TEMPLATES_LANG = 'en'

# Your language.
DEFAULT_LANG = 'de'
OG_LOCALE = 'de_DE'
LOCALE = 'de_DE'

**Comment by ncharlot** [comment]
Thx @alexandrevicenzi.

I did already try that but it's not working better...
Any idea?

This this the actual conf:
```pytho
I18N_TEMPLATES_LANG = 'en'
DEFAULT_LANG = 'fr'
LOCALE = 'fr_FR'
OG_LOCALE = 'fr_FR'

JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}

PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = ['i18n_subsites']
```

**Comment by alexandrevicenzi** [comment]
Try with German, Spanish or any other.

If none works is some Pelican misconfig. If not, it's a problem with the french translation.

**Comment by ncharlot** [comment]
So it seems to be a Pelican misconfig :(

**Comment by JesusMtnez** [comment]
In #73 I report a similar problem. Using pelican 3.6.3 it works.

**Comment by JesusMtnez** [comment]
@ncharlot what version are you using?

**Comment by ncharlot** [comment]
```
$ pip freeze
...
pelican==3.7.0
...
```

**Comment by JesusMtnez** [comment]
Try 3.6.3

**Comment by ncharlot** [comment]
Downgrade to 3.6.3 causes this error:
```
AttributeError: 'Environment' object has no attribute 'install_gettext_translations'
```

**Comment by JesusMtnez** [comment]
Replace 
```
JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}
```
with
```
JINJA_EXTENSIONS = ['jinja2.ext.i18n']
```

**Comment by ncharlot** [comment]
It's ok!

So it was a regression.

**Comment by alexandrevicenzi** [comment]
Actually it's a Flex bug, due the version 3.7.

**Comment by alexandrevicenzi** [comment]
Due the change in Pelican 3.7:

Old way

```JINJA_EXTENSIONS = ['jinja2.ext.i18n']```

New way

```JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}```


[This code](https://github.com/alexandrevicenzi/Flex/blob/master/templates/base.html#L1) breaks.

The solution is change the way we validade if i18n is enabled.

**Comment by ncharlot** [comment]
Ok I can look at the fix.

**Comment by alexandrevicenzi** [comment]
@ncharlot remember, It must work with 3.6 and 3.7, so we just need to add an `OR` statement.

**Comment by ncharlot** [comment]
Ok.

**Comment by ncharlot** [comment]
PR: https://github.com/alexandrevicenzi/Flex/pull/75

**Comment by alexandrevicenzi** [comment]
Fixed by #75

**Comment by Phyks** [comment]
Trying `master` with Pelican 3.7.1 and Jinja2 up to date, gives a `CRITICAL: UndefinedError: 'gettext' is undefined` error, when trying to use [this snippet](https://github.com/alexandrevicenzi/Flex/issues/74#issuecomment-271263179) in combination with `JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}`.

**Comment by alexandrevicenzi** [comment]
@Phyks what OS?

**Comment by Phyks** [comment]
I am using Linux.
